### ISSUE TITLE
TypeError: cli() got an unexpected keyword argument 'portal'

### ISSUE THREAD

**Issue by sirexx81** [mitsuhiko/flatex-pdf-download#9]
Receive an error when trying to download my documents:

Traceback (most recent call last):
  File "C:\python\flatex-fetch.py", line 292, in <module>
    cli()
  File "C:\python\Lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cli() got an unexpected keyword argument 'portal'

**Comment by mitsuhiko** [comment]
Sorry for that. Fixed in 09144a3f6e5af211566c8e7fd5ad0d3d97f3c63b

**Comment by sirexx81** [comment]
Hey, thanks for the quick fix.
However, I am still seeing an issue also with this version:

Traceback (most recent call last):
  File "C:\python\flatex-fetch.py", line 292, in <module>
    cli()
  File "C:\python\Lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\flatex-fetch.py", line 280, in cli
    fetcher.login(userid, password)
  File "C:\python\flatex-fetch.py", line 61, in login
    self.sso_url,
    ^^^^^^^^^^^^
  File "C:\python\flatex-fetch.py", line 57, in sso_url
    return PORTALS[self.portal]["sso_url"]
                   ^^^^^^^^^^^
AttributeError: 'Fetcher' object has no attribute 'portal'

**Comment by mitsuhiko** [comment]
Fixed and verified now :)
